# Generated by Django 5.2.5 on 2025-09-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0004_remove_announcement_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('maintenance', 'Maintenance'), ('food', 'Food'), ('facilities', 'Facilities'), ('inspection', 'Inspection')], default='general', max_length=50),
        ),
        migrations.DeleteModel(
            name='RoomChangeRequest',
        ),
    ]
