# Generated by Django 5.2.5 on 2025-09-11 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0006_rename_capacity_room_floor_room_block_room_has_ac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
