# Generated by Django 5.2.5 on 2025-09-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0009_studentregistry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fee_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', help_text='Current fee payment status', max_length=10),
        ),
    ]
